package:
    name: sls_detector
    version: developer

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - python
        - gcc_linux-64
        - gxx_linux-64
        - cmake
        - setuptools
        - sls_detector_lib developer
        - pyzmq
        - pybind11
        - libstdcxx-ng
        - libgcc-ng
    run:
        - python
        - cmake
        - numpy
        - sls_detector_lib developer
        - pyzmq
        - libstdcxx-ng
        - libgcc-ng


test:
      imports:
        - sls_detector



about:
    summary: "Interacting with detectors"
