package:
    name: sls_detector
    version: 3.0.1

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - python
        - gcc
        - cmake
        - setuptools
        - pybind11
        - sls_detector_software 3.0.1
        - pyzmq
    run:
        - python
        - gcc
        - cmake
        - numpy
        - sls_detector_software 3.0.1
        - pyzmq


test:
      imports:
         - sls_detector


about:
    summary: "Interacting with detectors"
