package:
    name: sls_detector
    version: developer

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - python
        - gcc
        - cmake
        - setuptools
        - pybind11
        - sls_detector_software developer
        - pyzmq 16.0.2
    run:
        - python
        - gcc
        - cmake
        - numpy
        - sls_detector_software developer
        - pyzmq 16.0.2


test:
      imports:
        - sls_detector



about:
    summary: "Interacting with detectors"
